-- MySQL Script generated by MySQL Workbench
-- Thu Jun 18 10:52:10 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema event_manager
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema event_manager
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `event_manager` DEFAULT CHARACTER SET utf8 ;
USE `event_manager` ;

-- -----------------------------------------------------
-- Table `event_manager`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_manager`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`category_id`));


-- -----------------------------------------------------
-- Table `event_manager`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_manager`.`events` (
  `idevents` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `type` VARCHAR(45) NULL,
  `date` DATE NULL,
  `location` VARCHAR(45) NULL,
  `description` MEDIUMTEXT NULL,
  `ticket_price` DECIMAL(10,2) NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`idevents`),
  INDEX `fk_events_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_events_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `event_manager`.`category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event_manager`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_manager`.`User` (
  `idUser` INT NOT NULL,
  `fullName` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event_manager`.`SavedEvents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event_manager`.`SavedEvents` (
  `idevents` INT NOT NULL,
  `idUser` INT NOT NULL,
  `idSave` VARCHAR(45) NOT NULL,
  `savedAt` DATETIME NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`idevents`, `idUser`, `idSave`),
  INDEX `fk_events_has_User_User1_idx` (`idUser` ASC) VISIBLE,
  INDEX `fk_events_has_User_events_idx` (`idevents` ASC) VISIBLE,
  CONSTRAINT `fk_events_has_User_events`
    FOREIGN KEY (`idevents`)
    REFERENCES `event_manager`.`events` (`idevents`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_events_has_User_User1`
    FOREIGN KEY (`idUser`)
    REFERENCES `event_manager`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
